# Skeleton form Ethan Sifferman
name: sim
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Download Tools
        run: |
          sudo apt-get install python3-dev
          pip3 install -r sw_utils/requirements.txt
          wget -O - https://raw.githubusercontent.com/sifferman/hdl-tool-installer/main/install | bash -s -- . --oss-cad-suite --zachjs-sv2v
          echo "$GITHUB_WORKSPACE/oss-cad-suite/bin" >> $GITHUB_PATH
          echo "$GITHUB_WORKSPACE/zachjs-sv2v" >> $GITHUB_PATH

      - run: make lint

      - run: make sim TOP=signed_div_tb

      - run: make clean